version: '3.1'
services:
  db:
    image: postgres:alpine
    container_name: albertsongs-db
    restart: always
    environment:
      - POSTGRES_DB=albertsongs
      - POSTGRES_USER=postgres
      - POSTGRES_HOST_AUTH_METHOD=trust
    volumes:
      - ./db_migration:/tmp/db_migration
  app:
    build: ./
    container_name: albertsongs-app
    restart: always
    ports:
      - '4433:443'
    environment:
      SERVER_PORT: 443
      SERVER_SSL_ENABLED: 'true'
      SERVER_SSL_KEY_STORE_TYPE: PKCS12
      SERVER_SSL_KEY_STORE: certificate.p12
      SERVER_SSL_KEY_STORE_PASSWORD:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db/albertsongs
      SPRING_DATASOURCE_USERNAME: postgres
    depends_on:
      - db