version: '3.1'
services:
  db:
    image: postgres:alpine
    restart: always
    environment:
      - POSTGRES_DB=albertsongs
      - POSTGRES_USER=postgres
      - POSTGRES_HOST_AUTH_METHOD=trust
  app:
    build: ./
    container_name: java-app
    restart: always
    ports:
      - '8080:8080'
    environment:
      SERVER_PORT: 8080
      SPRING_DATASOURCE_URL: jdbc:postgresql://db/albertsongs
      SPRING_DATASOURCE_USERNAME: postgres
      depends_on: db