spring:
  datasource:
    url: jdbc:postgresql://db/albertsongs
    username: postgres
    password:
  jpa:
    generate-ddl: true
    show-sql: true
  graphql:
    cors:
      allowed-origins:
        - https://albertsongs.github.io